
obj-$(CONFIG_HCC_GHOTPLUG) += ghotplug/
obj-$(CONFIG_HCC_GCAP) += capability/
obj-$(CONFIG_HCC_PROCFS) += procfs/
obj-$(CONFIG_HCC_PROC) += proc/
obj-$(CONFIG_HCC_DVFS) += fs/
obj-$(CONFIG_HCC_GPM) += gpm/ ghost/
obj-$(CONFIG_HCC_GMM) += gmm/
obj-$(CONFIG_HCC_GSCHED) += gscheduler/
