obj-$(CONFIG_HCC_GSCHED_THRESHOLD_FILTER) += threshold_filter.o
obj-$(CONFIG_HCC_GSCHED_FREQ_LIMIT_FILTER) += freq_limit_filter.o
obj-$(CONFIG_HCC_GSCHED_REMOTE_CACHE_FILTER) += remote_cache_filter.o

EXTRA_CFLAGS += -Wall -Werror
