
obj-$(CONFIG_KVM) += kvm/

# Xen paravirtualization support
obj-$(CONFIG_XEN) += xen/

# lguest paravirtualization support
obj-$(CONFIG_LGUEST_GUEST) += lguest/

# HCC SSI cluster support
obj-$(CONFIG_HCC) += hcc/

obj-y += kernel/
obj-y += mm/

obj-y += crypto/
obj-y += vdso/
obj-$(CONFIG_IA32_EMULATION) += ia32/

