obj-$(CONFIG_HCC_GSCHED_ECHO_POLICY) += echo_policy.o

obj-$(CONFIG_HCC_GSCHED_MOSIX_LOAD_BALANCER) += mosix_load_balancer.o
obj-$(CONFIG_HCC_GSCHED_ROUND_ROBIN_BALANCER) += round_robin_balancer.o

EXTRA_CFLAGS += -Wall -Werror
