obj-$(CONFIG_HCC_GSCHED_CPU_PROBE) += cpu_probe.o
obj-$(CONFIG_HCC_GSCHED_MEM_PROBE) += mem_probe.o

obj-$(CONFIG_HCC_GSCHED_MIGRATION_PROBE) += migration_probe.o
obj-$(CONFIG_HCC_GSCHED_MOSIX_PROBE) += mosix_probe.o

EXTRA_CFLAGS += -Werror -Wall
