#ifndef _HCC_GLOBALCAPABILITY_INTERNAL_H
#define _HCC_GLOBALCAPABILITY_INTERNAL_H

#ifdef CONFIG_HCC_GCAP

#include <linux/capability.h>



#endif // CONFIG_HCC_GCAP
#endif //_HCC_GLOBALCAPABILITY_INTERNAL_H